// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader {
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String, dynamic> ar = {
    "I_am_Usama": "أنا أسامة",
    "I_am_Developer": "أنا مطوِّر",
    "Onboarding_Screen_heading": "العنوان",
    "Onboarding_Screen_paragraph":
        "لوريم إيبسوم هو نص بديل يُستخدم في صناعة الطباعة والتصفيف. لوريم إيبسوم هو المعيار الصناعي.",
    "next_button_text": "التالي",
    "Continue_with_shortcode": "المتابعة باستخدام الشرطة",
    "shortcode": "الشرطة",
    "enter_your_shortcode": "أدخل الشرطة الخاصة بك",
    "Stay_logged_in": "البقاء مسجلاً؟",
    "login": "تسجيل الدخول",
    "enter_OTP": "أدخل رمز التحقق",
    "send": "إرسال",
    "Search_here": "البحث هنا",
    "Filter": "تصفية",
    "Your_Stats_are_Good_Keep_it_up": "إحصائياتك جيدة، استمر في العمل",
    "Total_Orders": "إجمالي الطلبات",
    "Order_Completion": "اكتمال الطلب",
    "On_Time_Delivery": "تسليم في الوقت المحدد",
    "Positive_Rating": "تقييم إيجابي",
    "Earning_Status": "حالة الأرباح",
    "Total_Earnings": "إجمالي الأرباح",
    "Active_Orders": "الطلبات النشطة",
    "Earnings_in_November": "الأرباح في نوفمبر",
    "Completed_Order": "الطلب المكتمل",
    "See_All": "عرض الكل",
    "In_Progress": "قيد التنفيذ",
    "Home": "الصفحة الرئيسية",
    "Orders": "الطلبات",
    "Profile": "الملف الشخصي",
    "Manage_Orders": "إدارة الطلبات",
    "Active": "نشط",
    "Pending": "قيد الانتظار",
    "Declined": "تم الرفض",
    "Completed": "مكتمل",
    "Location": "الموقع",
    "Edit_Profile": "تعديل الملف الشخصي",
    "My_Wallet": "محفظتي",
    "Settings": "الإعدادات",
    "Logout": "تسجيل الخروج",
    "Change_Password": "تغيير كلمة المرور",
    "Current_Language": "العربية",
    "Change_Language": "تغيير اللغة",
    "About_us": "من نحن",
    "Privacy_Policy": "سياسة الخصوصية",
    "Contact_us": "اتصل بنا",
    "Delete_Account": "حذف الحساب",
    "Update_Profile": "تحديث الملف الشخصي",
    "Available_Balance": "الرصيد المتاح",
    "Recent_Payments": "المدفوعات الأخيرة",
    "Feedback": "تقديم ملاحظات",
    "Select_a_Option": "اختر خيارًا",
    "Write_a_message": "كتابة رسالة",
    "Type_your_message": "اكتب رسالتك",
    "Submit": "إرسال",
    "Who_we_are": "من نحن",
    "Who_we_are_paragraph":
        "لوريم إيبسوم هو نص بديل يُستخدم في صناعة الطباعة والتصفيف. لوريم إيبسوم هو المعيار الصناعي.",
    "Our_Vision": "رؤيتنا",
    "Our_Vision_paragraph":
        "لوريم إيبسوم هو نص بديل يُستخدم في صناعة الطباعة والتصفيف. لوريم إيبسوم هو المعيار الصناعي.",
    "Terms_and_Condition": "الشروط والأحكام",
    "Terms_and_Condition_paragraph":
        "لوريم إيبسوم هو نص بديل يُستخدم في صناعة الطباعة والتصفيف. لوريم إيبسوم هو المعيار الصناعي.",
    "Privacy_Policy_Paragraph":
        "لوريم إيبسوم هو نص بديل يُستخدم في صناعة الطباعة والتصفيف. لوريم إيبسوم هو المعيار الصناعي.",
    "My_Services": "خدماتي",
    "create_new_service": "إنشاء خدمة جديدة",
    "create": "إنشاء",
    "by_creating_new_service":
        "من خلال إنشاء خدمة جديدة، ستكون خدمتك مرئية لآلاف المستخدمين. دعونا نقوم بإنشاء واحدة جديدة لك الآن!",
    "edit": "تحرير",
    "delete": "حذف",
    "Are_you_Sure_you_want_to_Delete_this_Service":
        "هل أنت متأكد أنك تريد حذف هذه الخدمة؟",
    "yes": "نعم",
    "cancel": "إلغاء",
  };
  static const Map<String, dynamic> en = {
    "I_am_Usama": "I am Usama",
    "I_am_Developer": "I am a Developer",
    "Onboarding_Screen_heading": "Tag Line",
    "Onboarding_Screen_paragraph":
        "Lorem Ipsum is simply placeholder text used in the printing and typesetting industry. Lorem Ipsum has been the industry standard.",
    "next_button_text": "Next",
    "Continue_with_shortcode": "Continue with shortcode",
    "shortcode": "Shortcode",
    "enter_your_shortcode": "Enter your shortcode",
    "Stay_logged_in": "Stay logged in?",
    "login": "Login",
    "enter_OTP": "Enter OTP",
    "send": "Send",
    "Search_here": "Search here",
    "Filter": "Filter",
    "Your_Stats_are_Good_Keep_it_up": "Your Stats are Good, Keep it up.",
    "Total_Orders": "Total Orders",
    "Order_Completion": "Order Completion",
    "On_Time_Delivery": "On-Time Delivery",
    "Positive_Rating": "Positive Rating",
    "Earning_Status": "Earning Status",
    "Total_Earnings": "Total Earnings",
    "Active_Orders": "Active Orders",
    "Earnings_in_November": "Earnings in November",
    "Completed_Order": "Completed Order",
    "See_All": "See All",
    "In_Progress": "In Progress",
    "Home": "Home",
    "Orders": "Orders",
    "Profile": "Profile",
    "Manage_Orders": "Manage Orders",
    "Active": "Active",
    "Pending": "Pending",
    "Declined": "Declined",
    "Completed": "Completed",
    "Location": "Location",
    "Edit_Profile": "Edit Profile",
    "My_Wallet": "My Wallet",
    "Settings": "Settings",
    "Logout": "Logout",
    "Change_Password": "Change Password",
    "Current_Language": "ENG",
    "Change_Language": "Change Language",
    "About_us": "About us",
    "Privacy_Policy": "Privacy Policy",
    "Contact_us": "Contact us",
    "Delete_Account": "Delete Account",
    "Update_Profile": "Update Profile",
    "Available_Balance": "Available Balance",
    "Recent_Payments": "Recent Payments",
    "Feedback": "Feedback",
    "Select_a_Option": "Select a Option",
    "Write_a_message": "Write a message",
    "Type_your_message": "Type your message",
    "Submit": "Submit",
    "Who_we_are": "Who we are",
    "Who_we_are_paragraph":
        "Lorem Ipsum is simply placeholder text used in the printing and typesetting industry. Lorem Ipsum has been the standard placeholder text of the industry since the 1500s when an unidentified printer took a collection of type and jumbled it to create a sample book. It has endured not only for five centuries but also made the transition to electronic typesetting, remaining essentially unaltered",
    "Our_Vision": "Our Vision",
    "Our_Vision_paragraph":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and changed",
    "Terms_and_Condition": "Terms and Condition",
    "Terms_and_Condition_paragraph":
        "Lorem Ipsum is simply placeholder text used in the printing and typesetting industry. Lorem Ipsum has been the standard placeholder text of the industry since the 1500s when an unidentified printer took a collection of type and jumbled it to create a sample book. It has endured not only for five centuries but also made the transition to electronic typesetting, remaining essentially unaltered",
    "Privacy_Policy_Paragraph":
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and changed",
    "My_Services": "My Services",
    "create_new_service": "Create a new service",
    "create": "Create",
    "by_creating_new_service":
        "By Creating a new service, your service will be visible to thousand of Users. Lets Make a New one for you now!",
    "edit": "Edit",
    "delete": "Delete",
    "Are_you_Sure_you_want_to_Delete_this_Service":
        "Are you Sure you want to Delete this Service?",
    "yes": "Yes",
    "cancel": "Cancel"
  };
  static const Map<String, dynamic> ur = {
    "I_am_Usama": "میں اسامہ ہوں",
    "I_am_Developer": "میں ڈویلپر ہوں",
    "Onboarding_Screen_heading": "عنوان",
    "Onboarding_Screen_paragraph":
        "لورم اپسم کے بصرف کچھ وقت کے لئے متن ہوتا ہے جو چھپائی اور ٹائپ سیٹ کاری کی صنعت میں استعمال ہوتا ہے۔ لورم اپسم کو صنعت کا معیار بنایا گیا ہے۔",
    "next_button_text": "اگلا",
    "Continue_with_shortcode": "شارٹ کوڈ کے ساتھ جاری رہیں",
    "shortcode": "شارٹ کوڈ",
    "enter_your_shortcode": "اپنا شارٹ کوڈ درج کریں",
    "Stay_logged_in": "لاگ ان رہیں؟",
    "login": "لاگ ان",
    "enter_OTP": "OTP درج کریں",
    "send": "بھیجیں",
    "Search_here": "یہاں تلاش کریں",
    "Filter": "فلٹر",
    "Your_Stats_are_Good_Keep_it_up":
        "آپ کی اشیاء اچھی ہیں، اسی طرح جاری رکھیں۔",
    "Total_Orders": "کل آرڈرز",
    "Order_Completion": "آرڈر مکمل ہونے",
    "On_Time_Delivery": "وقت پر تسلیم",
    "Positive_Rating": "مثبت ریٹنگ",
    "Earning_Status": "کمائی کی حالت",
    "Total_Earnings": "کل کمائی",
    "Active_Orders": "فعال آرڈرز",
    "Earnings_in_November": "نومبر میں کمائی",
    "Completed_Order": "مکمل آرڈر",
    "See_All": "سب دیکھیں",
    "In_Progress": "کام جاری ہے",
    "Home": "ہوم",
    "Orders": "آرڈرز",
    "Profile": "پروفائل",
    "Manage_Orders": "آرڈرز منظم کریں",
    "Active": "فعال",
    "Pending": "زیر التواء",
    "Declined": "منظور نہیں",
    "Completed": "مکمل",
    "Location": "مقام",
    "Edit_Profile": "پروفائل ترتیب دیں",
    "My_Wallet": "میری والٹ",
    "Settings": "ترتیبات",
    "Logout": "لاگ آوٹ",
    "Change_Password": "پاس ورڈ تبدیل کریں",
    "Current_Language": "اردو",
    "Change_Language": "زبان تبدیل کریں",
    "About_us": "ہمارے بارے میں",
    "Privacy_Policy": "رازداری کی پالیسی",
    "Contact_us": "ہم سے رابطہ کریں",
    "Delete_Account": "اکاؤنٹ حذف کریں",
    "Update_Profile": "پروفائل اپ ڈیٹ کریں",
    "Available_Balance": "موجودہ بیلنس",
    "Recent_Payments": "حالیہ ادائیگیاں",
    "Feedback": "رائے",
    "Select_a_Option": "ایک آپشن منتخب کریں",
    "Write_a_message": "پیغام لکھیں",
    "Type_your_message": "اپنا پیغام ٹائپ کریں",
    "Submit": "جمع کریں",
    "Who_we_are": "ہم کون ہیں",
    "Who_we_are_paragraph":
        "لورم اپسم کے بصرف کچھ وقت کے لئے متن ہوتا ہے جو چھپائی اور ٹائپ سیٹ کاری کی صنعت میں استعمال ہوتا ہے۔ لورم اپسم کو صنعت کا معیار بنایا گیا ہے۔",
    "Our_Vision": "ہمارا ویژن",
    "Our_Vision_paragraph":
        "لورم اپسم کے بصرف کچھ وقت کے لئے متن ہوتا ہے جو چھپائی اور ٹائپ سیٹ کاری کی صنعت میں استعمال ہوتا ہے۔ لورم اپسم کو صنعت کا معیار بنایا گیا ہے۔",
    "Terms_and_Condition": "شرائط و ضوابط",
    "Terms_and_Condition_paragraph":
        "لورم اپسم کے بصرف کچھ وقت کے لئے متن ہوتا ہے جو چھپائی اور ٹائپ سیٹ کاری کی صنعت میں استعمال ہوتا ہے۔ لورم اپسم کو صنعت کا معیار بنایا گیا ہے۔",
    "Privacy_Policy_Paragraph":
        "لورم اپسم کے بصرف کچھ وقت کے لئے متن ہوتا ہے جو چھپائی اور ٹائپ سیٹ کاری کی صنعت میں استعمال ہوتا ہے۔ لورم اپسم کو صنعت کا معیار بنایا گیا ہے۔",
    "My_Services": "میری خدمات",
    "create_new_service": "نیا خدمت بنائیں",
    "create": "بنائیں",
    "by_creating_new_service":
        "نئی خدمت بنا کر، آپ کی خدمت ہزاروں صارفین کو دکھائی جائے گی۔ ہم اب آپ کے لیے ایک نیا بناتے ہیں!",
    "edit": "ترتیب دیں",
    "delete": "حذف کریں",
    "Are_you_Sure_you_want_to_Delete_this_Service":
        "کیا آپ یقینی ہیں کہ آپ یہ خدمت حذف کرنا چاہتے ہیں؟",
    "yes": "جی ہاں",
    "cancel": "منسوخ کریں"
  };
  static const Map<String, Map<String, dynamic>> mapLocales = {
    "ar": ar,
    "en": en,
    "ur": ur
  };
}
